# Generated by Django 4.1.3 on 2022-11-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='categories',
            new_name='category',
        ),
    ]
